### ISSUE TITLE
使用 Github Actions 每天自动发送比特币的估值邮件

### ISSUE THREAD

**Issue by latinos-bub** [ireflux/bitcoin-action#1]
sherry, 你好
   我也是看了阮老师的每天发送邮件的博客和你的[使用 Github Actions 每天自动发送比特币的估值邮件](https://wanmei.ml/snow/post/send-mail-with-bitcoin-rate-everyday/#heading)博客后，也想搞一个这样的例子，但是我在使用中一直解决不了一个问题，就是会一直报一个错误：`Error: 535-5.7.8 Username and Password not accepted. 。。。` ，我在 secrets 中已经配置了相应的 MAIL_USERNAME 和 MAIL_PASSWORD了，我使用的是 gmail，自认为账号和密码应该没写错，但是不知道这个问题的缘故是不是gmail需要特别设置还是我填写的有问题？（如有空的话，麻烦看一下我的配置文件 `https://github.com/latinos-bub/weather-action` , 不胜感激）

**Comment by ireflux** [comment]
@latinos-bub 抱歉，刚看到（平时不怎么看Issue）
是因为 Gmail 的安全策略的问题，被阻止了，我试了一下，得到了如下警示：

> Google blocked the app you were trying to use because it doesn't meet our security standards.
> Some apps and devices use less secure sign-in technology, which makes your account more vulnerable. You can turn off access for these apps, which we recommend, or turn on access if you want to use them despite the risks. Google will automatically turn this setting OFF if it's not being used.

你可以查看[官方文档](https://support.google.com/accounts/answer/6010255?p=lsa_blocked)来关闭这个安全策略。希望能够帮到你。
